app/models/job.py
from app.db import db
from sqlalchemy.sql import func


class Job(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200))
    url = db.Column(db.String(500))
    company = db.Column(db.String(200))
    web_portal = db.Column(db.String(100))
    modality = db.Column(db.String(100))
    applicationDate = db.Column(db.Date(), default=func.now())
    publicationDate = db.Column(db.Date)

    def __init__(self, name, url, company, web_portal, modality, publicationDate):
        self.name = name
        self.url = url
        self.company = company
        self.web_portal = web_portal
        self.modality = modality
        self.publicationDate = publicationDate

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import Config
from .routes.index import jobs_router
from app.db import db


def create_app():
    
    app = Flask(__name__)
    Bootstrap(app)
    app.config.from_object(Config)
    app.register_blueprint(jobs_router)
    db.init_app(app)
    
    return app

app/routes/index.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.job import Job
from app.db import db

jobs_router = Blueprint("jobs", __name__)


@jobs_router.route("/")
def index():
    jobs = Job.query.all()
    return render_template("index.html", jobs=jobs)


@jobs_router.route("/new-job", methods=["GET", "POST"])
def create_job():
    if request.method == "GET":
        return render_template("create.html")
    
    elif request.method == "POST":
        name = request.form["name"]
        url = request.form["url"]
        company = request.form["company"]
        web_portal = request.form["web_portal"]
        modality = request.form["modality"]
        publicationDate = request.form["publicationDate"]

        new_job = Job(name, url, company, web_portal, modality, publicationDate)

        db.session.add(new_job)
        db.session.commit()

        return redirect(url_for("jobs.index")), 201


@jobs_router.route("/update-job/<id>", methods=["GET", "PUT"])
def update_job(id):
    job = Job.query.get(id)

    if request.method == "GET":
        return render_template("update.html", job=job)

    elif request.method == "PUT":
        job.name = request.form["name"]
        job.url = request.form["url"]
        job.company = request.form["company"]
        job.web_portal = request.form["web_portal"]
        job.modality = request.form["modality"]
        job.publicationDate = request.form["publicationDate"]

        db.session.commit()

        return jsonify({"message": "Job updated successfully"}), 200


@jobs_router.route("/delete-job/<id>", methods=["DELETE"])
def delete_job(id):
    job = Job.query.get(id)
    db.session.delete(job)
    db.session.commit()

    return jsonify({"message": "Job deleted successfully"}), 204

app/templates/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/main.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <title>Postulated Jobs</title>
  </head>
  <body class="gradient-custom">
    <header>
        <nav class="navbar navbar-expand-lg p-4">
          <a class="navbar-brand text-light" href="/">JOB CRUD</a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link text-light" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="/new-job">Create job</a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
    <div class="d-flex justify-content-center">
        <div class="card p-4 mt-4 mb-4 shadow-lg" style="width: 27rem">
          <h1 class="text-center">Create Job</h1>
          <form action="/new-job" method="POST" onsubmit="createJob(event)">
            <div class="mb-3">
              <label class="form-label">Name:</label>
              <input class="form-control" type="text" name="name" />
            </div>
            <div class="mb-3">
              <label class="form-label">Url:</label>
              <input class="form-control" type="text" name="url" />
            </div>
            <div class="mb-3">
              <label class="form-label">Company:</label>
              <input class="form-control" type="text" name="company" />
            </div>
            <div class="mb-3">
              <label class="form-label">Web Portal:</label>
              <input class="form-control" type="text" name="web_portal" />
            </div>
            <div class="mb-3">
              <label class="form-label">Modality:</label>
              <input class="form-control" type="text" name="modality" />
            </div>
            <div class="mb-3">
              <label class="form-label">Publication Date:</label>
              <input class="form-control" type="date" name="publicationDate" />
            </div>
            <div class="row d-flex mx-2">
                <button tyte="submit" class="btn btn-primary mb-3">Save</button>
                <a class="btn btn-danger" href="/">Cancel</a>
              </div>
          </form>
        </div>
      </div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{{ url_for('static', filename='js/creation-alert.js') }}"></script>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/main.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <title>Jobs CRUD Flask</title>
  </head>
 <body class="gradient-custom">
    <header>
      <nav class="navbar navbar-expand-lg p-4">
        <a class="navbar-brand text-light" href="/">JOB CRUD</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link text-light" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/new-job">Create job</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Jobs list -->
    <div class="container mt-4 mb-4">
      <h1 class="text-center text-light">Postulated Jobs</h1>
      <div class="row d-flex justify-content-center align-items-center mt-4">
        {% for job in jobs %}
        <div class="col-md-8 col-lg-4 my-3">
          <div class="card text-center p-4 shadow-lg">
            <div class="card-body">
              <h5 class="card-title mb-4">{{ job.name }}</h5>
              <p class="card-text">Company: {{ job.company }}</p>
              <p class="card-text">Modality: {{ job.modality }}</p>
              <p class="card-text">
                Application Date: {{ job.applicationDate }}
              </p>
              <p class="card-text">Web portal: {{ job.web_portal }}</p>
              <a href="{{job.url}}" class="btn btn-info my-2">Job link</a>
            </div>
            <div class="row d-flex mx-4">
              <a
                class="btn btn-primary mb-2"
                href="{{url_for('jobs.update_job', id=job.id)}}"
                role="button"
                >Edit</a
              >
              <button
                class="btn btn-danger"
                data-jobid="{{ job.id }}"
                role="button"
                onclick="deleteJobConfirmation(event, this.dataset.jobid)"
                >Delete</button
              >
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{{ url_for('static', filename='js/creation-alert.js') }}"></script>
  <script src="{{ url_for('static', filename='js/delete-alert.js') }}"></script>
</html>

app/templates/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/main.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <title>Update Job</title>
  </head>
  <body class="gradient-custom">
    <header>
      <nav class="navbar navbar-expand-lg p-4">
        <a class="navbar-brand text-light" href="/">JOB CRUD</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link text-light" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/new-job">Create job</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Job Update Form -->
    <div class="d-flex justify-content-center">
      <div class="card p-4 mt-4 mb-4 shadow-lg" style="width: 27rem">
        <h1 class="text-center">Update Job</h1>
        <form onsubmit="updateJob(event, '{{ job.id }}')" method="POST">
          <div class="mb-3">
            <label class="form-label">Name:</label>
            <input
              class="form-control"
              type="text"
              name="name"
              value="{{job.name}}"
            />
          </div>
          <div class="mb-3">
            <label class="form-label">Url:</label>
            <input
              class="form-control"
              type="text"
              name="url"
              value="{{job.url}}"
            />
          </div>
          <div class="mb-3">
            <label class="form-label">Company:</label>
            <input
              class="form-control"
              type="text"
              name="company"
              value="{{job.company}}"
            />
          </div>
          <div class="mb-3">
            <label class="form-label">Web Portal:</label>
            <input
              class="form-control"
              type="text"
              name="web_portal"
              value="{{job.web_portal}}"
            />
          </div>
          <div class="mb-3">
            <label class="form-label">Modality:</label>
            <input
              class="form-control"
              type="text"
              name="modality"
              value="{{job.modality}}"
            />
          </div>
          <div class="mb-4">
            <label class="form-label">Publication Date:</label>
            <input
              class="form-control"
              type="date"
              name="publicationDate"
              value="{{job.publicationDate}}"
            />
          </div>
          <div class="row d-flex mx-2">
            <button tyte="submit" class="btn btn-success mb-3">Update</button>
            <a class="btn btn-danger" href="/">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{{ url_for('static', filename='js/update-alert.js') }}"></script>
</html>